# Pıtırcık ve Gökkuşağının Kayıp Renkleri — senaryo
# Her sahne tek bir seslendirme parçasıdır (<=1000 karakter).
# Her satır: (metin, konuşan, olaylar)
# konuşan: anlatici / pitircik / baykus / pamuk / civil / virak
SCENES = [
 dict(id="s1", bg="orman", lines=[
  ("Merhaba çocuklar! Hoş geldiniz!", "anlatici", []),
  ("Bugün size minik ve meraklı bir kirpinin, Pıtırcık'ın hikâyesini anlatacağım.", "anlatici", ["enter:pitircik"]),
  ("Pıtırcık, ormanın kenarındaki küçük bir yuvada yaşardı. Sırtında yumuşacık dikenleri, burnunun ucunda da minik bir benek vardı.", "anlatici", []),
  ("Dün gece ormanda kocaman bir fırtına çıktı.", "anlatici", ["storm"]),
  ("Rüzgâr vuuu diye esti, yağmur şıp şıp yağdı, gök de güm güm gürledi.", "anlatici", ["storm"]),
  ("Sabah olunca fırtına dindi. Pıtırcık yuvasından çıktı, gözlerini ovuşturdu ve gökyüzüne baktı.", "anlatici", ["calm"]),
  ("Aaa! Gökkuşağı gri olmuş! Bütün renkleri kaybolmuş!", "pitircik", ["surprise"]),
  ("O sırada yaşlı meşe ağacının dalından Bilge Baykuş seslendi.", "anlatici", ["enter:baykus"]),
  ("Günaydın Pıtırcık! Fırtına gökkuşağının renklerini ormana dağıttı. Onları bulup geri getirmeliyiz.", "baykus", []),
  ("Gökkuşağının tam yedi rengi var: kırmızı, turuncu, sarı, yeşil, mavi, lacivert ve mor.", "baykus", ["show_colors"]),
  ("Pıtırcık küçük sepetini kaptı: Merak etme Bilge Baykuş, ben bütün renkleri bulacağım!", "pitircik", ["basket"]),
  ("Sen de bana yardım eder misin? Harika! Haydi, ilk rengi bulmaya gidelim!", "pitircik", ["pause:1.5"]),
 ]),
 dict(id="s2", bg="bahce", lines=[
  ("Pıtırcık tıpış tıpış yürüdü, yürüdü ve güzel bir bahçeye geldi.", "anlatici", ["walk"]),
  ('Yolda kuşlar ötüyor, arılar vızır vızır uçuyordu. Pıtırcık da neşeyle şarkı söylüyordu: Renkleri bulacağım, gökkuşağına götüreceğim!', 'pitircik', []),
  ("Bahçede kocaman yeşil yapraklar vardı. Yaprakların altından da kıpkırmızı bir şeyler göz kırpıyordu.", "anlatici", []),
  ("Bunlar çilek! Ama hepsi yaprakların altına saklanmış. Haydi, çilekleri birlikte sayalım!", "pitircik", ["pause:0.8"]),
  ("Bir!", "pitircik", ["count:1"]),
  ("İki!", "pitircik", ["count:2"]),
  ("Üç!", "pitircik", ["count:3"]),
  ("Dört!", "pitircik", ["count:4"]),
  ("Beş!", "pitircik", ["count:5"]),
  ("Tam beş tane çilek! Aferin size, çok güzel saydınız!", "pitircik", ["pause:1.0"]),
  ("Pıtırcık çileklere teşekkür etti. Çilekler de mutlu oldu ve parlamaya başladı.", "anlatici", ["sparkle"]),
  ("Parlayan çileklerin içinden minik bir ışık uçtu. Bu, gökkuşağının ilk rengiydi.", "anlatici", []),
  ("Bu renk ne renk? Hadi, sen söyle!", "anlatici", ["pause:2.5"]),
  ("Evet! Kırmızı! Bildin! Pıtırcık kırmızı rengi dikkatlice sepetine koydu.", "pitircik", ["collect:0"]),
  ("Kırmızı renkli başka neler var? Elma kırmızı, domates kırmızı, itfaiye arabası da kırmızı!", "anlatici", ["items:elma,domates,itfaiye"]),
  ('Senin evinde kırmızı renkli ne var? Etrafına bir bak bakalım!', 'anlatici', ['pause:2.5']),
  ('Pıtırcık sepetine baktı: Bir renk buldum, altı renk kaldı! Haydi, yola devam!', 'pitircik', ['pause:0.8']),
 ]),
 dict(id="s3", bg="tarla", lines=[
  ("Pıtırcık yoluna devam etti. Biraz ileride, bir sebze tarlasında küçük bir tavşan ağlıyordu.", "anlatici", ["walk", "enter:pamuk"]),
  ("Merhaba! Benim adım Pıtırcık. Neden ağlıyorsun?", "pitircik", []),
  ("Benim adım Pamuk. Havuçlarımı topraktan çıkaramıyorum. Çok sıkı gömülmüşler, ben de çok küçüğüm.", "pamuk", []),
  ("Üzülme Pamuk! Birlikte çekersek başarırız. Hazır mısın? Bir, iki, üç, çek!", "pitircik", ["pull"]),
  ("Pıtırcık havucun yapraklarından tuttu, Pamuk da Pıtırcık'ı belinden tuttu.", 'anlatici', ['pull']),
  ("Pıt! Birinci havuç çıktı.", "anlatici", ["carrot:1"]),
  ("Pıt! İkinci havuç çıktı.", "anlatici", ["carrot:2"]),
  ("Pıt! Üçüncü havuç da çıktı!", "anlatici", ["carrot:3"]),
  ("Kaç havuç çıkardılar? Üç! Bravo!", "anlatici", ["pause:1.2"]),
  ("Teşekkür ederim Pıtırcık! Birlikte çalışınca her şey ne kadar kolay oluyor.", "pamuk", []),
  ("Havuçların üzerinde turuncu bir ışık parlıyordu. Bu da gökkuşağının ikinci rengi: turuncu!", "anlatici", ["sparkle", "collect:1"]),
  ("Portakal turuncu, balkabağı turuncu, havuç da turuncu!", "anlatici", ["items:portakal,balkabagi,havuc"]),
  ("Pamuk da maceraya katılmak istedi. Artık iki arkadaştılar!", "anlatici", ["pause:1.0"]),
  ("Pamuk havuçlardan birini Pıtırcık'a uzattı: Bu sana, yolda acıkırsan ye! Paylaşmak çok güzeldir.", 'pamuk', []),
  ('Pıtırcık çok sevindi: Teşekkür ederim Pamuk! Haydi, üçüncü rengi bulalım!', 'pitircik', ['pause:0.8']),
 ]),
 dict(id="s4", bg="aycicegi", lines=[
  ("İki arkadaş el ele tutuştu ve kocaman ayçiçeklerinin olduğu bir tarlaya geldiler.", "anlatici", ["walk", "enter:civil"]),
  ("Ayçiçeklerinin üstünde minik, sarı bir kuş şarkı söylüyordu. Adı Cıvıl'dı.", "anlatici", []),
  ('Ayçiçekleri yüzlerini hep güneşe çevirirdi. Sabah doğuya, akşam batıya bakarlardı.', 'anlatici', []),
  ("Bazı ayçiçekleri Pıtırcık'tan bile on kat daha uzundu!", 'anlatici', []),
  ("Cik cik! Merhaba arkadaşlar! Siz kayıp renkleri mi arıyorsunuz? Ben sarı rengi gördüm. Güneş gibi parlak bir renk!", "civil", []),
  ("Peki, sarı renkli başka neler biliyorsunuz çocuklar?", "anlatici", ["pause:2.5"]),
  ("Çok güzel! Güneş sarı. Muz sarı. Limon da sarı!", "civil", ["items:gunes,muz,limon"]),
  ("Haydi, ayçiçeklerini sayalım!", "pitircik", []),
  ("Bir!", "pitircik", ["count:1"]),
  ("İki!", "pitircik", ["count:2"]),
  ("Üç!", "pitircik", ["count:3"]),
  ("Dört!", "pitircik", ["count:4"]),
  ("Dört ayçiçeği! En büyük ayçiçeğinin ortasından sarı bir ışık uçtu ve sepete kondu.", "anlatici", ["sparkle"]),
  ("Üçüncü renk: sarı!", "anlatici", ["collect:2"]),
  ("Cıvıl da onlara katıldı ve şarkı söyleyerek yol gösterdi. Artık üç arkadaştılar!", "anlatici", ["pause:1.0"]),
  ('Cıvıl kanatlarını çırptı ve küçük bir şarkı söyledi: Cik cik cik, renkler bizim, cik cik cik, arkadaşız biz!', 'civil', []),
  ('Haydi, sen de Cıvıl gibi kollarını kanat yap ve çırp! Çırp, çırp, çırp!', 'anlatici', ['flap', 'pause:2.0']),
 ]),
 dict(id="s5", bg="gol", lines=[
  ("Üç arkadaş, ormanın içindeki küçük ve sakin bir göle vardılar.", "anlatici", ["walk", "enter:virak"]),
  ("Gölün üstünde yuvarlak nilüfer yaprakları vardı. Yaprakların üstünde de neşeli bir kurbağa zıplıyordu.", "anlatici", []),
  ('Gölde ördekler yüzüyor, yusufçuklar suyun üstünde dans ediyordu.', 'anlatici', []),
  ('Bir ördek anne, arkasında üç yavrusuyla yüzüp geçti. Vak vak vak!', 'anlatici', []),
  ("Vırak vırak! Ben Kurbağa Vırak! Yeşil rengi arıyorsanız, yapraklarımın üstünden zıplamanız gerek!", "virak", []),
  ("Ama ben zıplamayı bilmiyorum ki!", "pitircik", []),
  ("Hiç merak etme! Önce dizlerini bük, sonra kollarını salla ve zıpla! Hadi, sen de evde bizimle zıpla!", "virak", ["pause:0.8"]),
  ("Hop!", "anlatici", ["hop:1"]),
  ("Hop!", "anlatici", ["hop:2"]),
  ("Hop!", "anlatici", ["hop:3"]),
  ("Kaç yapraktan zıpladık? Üç! Çok güzel zıpladın!", "pitircik", ["pause:1.0"]),
  ("Son yaprağın üstünde yeşil bir ışık parlıyordu. Dördüncü renk: yeşil!", "anlatici", ["sparkle", "collect:3"]),
  ("Ağaçlar yeşil, çimenler yeşil, Vırak da yeşil!", "anlatici", ["items:agac,cimen,kurbaga"]),
  ('Sence yeşil renkli başka ne var? Belki bir salatalık, belki bir yaprak?', 'anlatici', ['pause:2.0']),
  ("Vırak arkadaşlarına el salladı: Yolunuz açık olsun! Vırak vırak!", "virak", ["pause:1.0"]),
  ("Pıtırcık ve arkadaşları Vırak'a teşekkür ettiler ve yola koyuldular. Sepette artık dört renk vardı.", 'anlatici', []),
 ]),
 dict(id="s6", bg="dere", lines=[
  ("Arkadaşlar yürümeye devam ettiler ve şırıl şırıl akan bir dereye geldiler.", "anlatici", ["walk"]),
  ("Derenin suyu masmaviydi. İçinde de minik balıklar yüzüyordu.", "anlatici", []),
  ('Pamuk suya baktı: Aaa, suda kendimi görüyorum! Kulaklarım ne kadar uzunmuş!', 'pamuk', []),
  ('Herkes güldü. Hi hi hi! Ha ha ha!', 'anlatici', ['laugh']),
  ('Balıklar da onlara katıldı ve suyun içinde blup blup diye baloncuklar çıkardılar.', 'anlatici', ['bubbles']),
  ("Bakın! Balıklar bize bir şey göstermek istiyor! Haydi, balıkları sayalım!", "pitircik", []),
  ("Bir, iki, üç!", "pitircik", ["count:1", "count:2", "count:3"]),
  ("Dört, beş, altı!", "pitircik", ["count:4", "count:5", "count:6"]),
  ("Altı balık! Balıklar suyun üstüne zıpladı ve mavi bir ışık sepete uçtu.", "anlatici", ["sparkle"]),
  ("Beşinci renk: mavi! Gökyüzü mavi, deniz mavi, bu dere de mavi!", "anlatici", ["collect:4"]),
  ("Derenin dibinde koyu renkli, parlak taşlar vardı. Cıvıl hemen suya eğildi ve bir taş buldu.", "anlatici", ["stones"]),
  ("Cik cik! Bu taşın rengi koyu mavi. Koyu maviye lacivert denir!", "civil", []),
  ("Altıncı renk: lacivert!", "anlatici", ["sparkle", "collect:5"]),
  ('Pıtırcık taşı sepete koyarken saydı: Kırmızı, turuncu, sarı, yeşil, mavi ve lacivert!', 'pitircik', []),
  ("Sepette altı renk var. Bir renk daha kaldı! Sence son renk hangisi?", "anlatici", ["pause:2.5"]),
 ]),
 dict(id="s7", bg="lavanta", lines=[
  ("Güneş batmaya başlamıştı. Arkadaşlar mis kokulu bir lavanta tarlasına geldiler.", "anlatici", ["walk"]),
  ("Lavantalar mor renkliydi ve etraflarında rengârenk kelebekler uçuyordu.", "anlatici", []),
  ('Pıtırcık, Pamuk ve Cıvıl lavantaların arasında yavaşça yürüdüler.', 'anlatici', []),
  ('Hımm, ne güzel kokuyor! Haydi, sen de burnunla derin bir nefes al. Hıııı... Ve ver. Ohhh!', 'anlatici', ['pause:2.0']),
  ("Ama Pıtırcık çok yorulmuştu. Minik ayakları ağrıyordu, sepeti de ağırlaşmıştı.", "anlatici", ["tired"]),
  ("Of... Ben artık yürüyemiyorum arkadaşlar.", "pitircik", ["tired"]),
  ("Merak etme Pıtırcık! Sepeti ben taşırım!", "pamuk", ["help"]),
  ("Ben de sana yolu gösteririm! Cik cik!", "civil", ["help"]),
  ("Arkadaşlar böyledir, birbirlerine yardım ederler. Pıtırcık gülümsedi ve biraz dinlendi.", "anlatici", ["rested"]),
  ('Sen de arkadaşlarına yardım ediyor musun? Oyuncaklarını paylaşıyor musun? Ne güzel!', 'anlatici', ['pause:1.5']),
  ("Haydi, kelebekleri sayalım!", "anlatici", []),
  ("Bir, iki, üç!", "anlatici", ["count:1", "count:2", "count:3"]),
  ("Üç kelebek lavantaların üstünde döndü, döndü ve mor bir ışık getirdi.", "anlatici", ["sparkle"]),
  ("Yedinci ve son renk: mor! Üzüm mor, patlıcan mor, lavanta da mor!", "anlatici", ["collect:6", "items:uzum,patlican,lavanta"]),
  ("Bütün renkler tamam! Haydi, Bilge Baykuş'a dönelim!", "pitircik", ["pause:1.0"]),
  ('Güneş batarken gökyüzü turuncu ve pembe oldu. Arkadaşlar acele etmeliydi.', 'anlatici', []),
 ]),
 dict(id="s8", bg="final", lines=[
  ("Arkadaşlar koşa koşa Bilge Baykuş'un ağacına döndüler.", "anlatici", ["walk", "enter:baykus"]),
  ('Gökkuşağı hâlâ griydi ve onları bekliyordu.', 'anlatici', []),
  ("Aferin size! Yedi rengin hepsini bulmuşsunuz. Şimdi renkleri gökyüzüne gönderelim. Hep birlikte söyleyelim!", "baykus", ["pause:0.5"]),
  ("Kırmızı!", "anlatici", ["rainbow:0"]),
  ("Turuncu!", "anlatici", ["rainbow:1"]),
  ("Sarı!", "anlatici", ["rainbow:2"]),
  ("Yeşil!", "anlatici", ["rainbow:3"]),
  ("Mavi!", "anlatici", ["rainbow:4"]),
  ("Lacivert!", "anlatici", ["rainbow:5"]),
  ("Ve mor!", "anlatici", ["rainbow:6"]),
  ("Gökkuşağı yeniden rengârenk oldu! Kuşlar şarkı söyledi, bütün orman alkışladı!", "anlatici", ["celebrate", "pause:1.5"]),
  ('Pamuk sevinçten zıpladı, Cıvıl şarkı söyledi, Pıtırcık da dikenlerini kabartıp dans etti!', 'anlatici', ['celebrate']),
  ('Haydi, sen de onlarla birlikte dans et! Sağa, sola, zıpla, dön!', 'anlatici', ['celebrate', 'pause:2.5']),
  ("Pıtırcık gülümsedi: Arkadaşlarım olmasaydı bunu başaramazdım. Birlikte her şey daha güzel!", "pitircik", ["celebrate"]),
  ('Bilge Baykuş kanatlarını açtı: Bugün çok şey öğrendiniz. Renkleri tanıdınız, saymayı öğrendiniz, en önemlisi de yardımlaşmayı!', 'baykus', []),
  ("Sen de bugün bize çok yardım ettin. Renkleri bildin, saymayı yaptın, zıpladın! Teşekkürler!", "anlatici", ["celebrate"]),
  ('O gece Pıtırcık yuvasına döndü ve rengârenk rüyalar gördü. İyi geceler Pıtırcık!', 'anlatici', ['night']),
  ("Bir sonraki macerada görüşmek üzere, hoşça kal!", "anlatici", ["wave", "pause:2.0"]),
 ]),
]
def scene_text(s): return " ".join(l[0] for l in s["lines"])
if __name__ == "__main__":
    t=0
    for s in SCENES:
        n=len(scene_text(s)); t+=n; print(s["id"], n)
    print("toplam", t)
